config/routes.rb
Rails.application.routes.draw do
  # root to: 'sessions#new'
  root to: 'images#new'
  # get 'auth/google_oauth2/callback', to: 'oauth2#redirect'
  get 'auth/google_oauth2/callback', to: 'sessions#create', as: :sign_in
  delete '/sign_out', to: 'sessions#destroy', as: 'sign_out'
  get 'auth/failure', to: redirect('/')
  get '/auth/google_oauth2', as: 'google_oauth2'
  resources :pdfs
  # get '/sign_in', to: 'sessions#new'
  resources :sessions, only: [:create, :destroy]
  # post '/sign_in', to: 'sessions#create', as: 'sessions'
  post 'apply_watermark', to: 'watermarker#apply', as: 'apply_watermark'
  get 'progress/:job_id', to: 'watermarker#percentage_done'

  resources :users, only: [:new, :create]
  resources :images, only: [:new, :create, :show, :index]
  resources :projects, only: [:new, :create, :index, :show] do
    resources :pdfs, only: [:create]
  end

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/models/project.rb
class Project < ActiveRecord::Base
  validates_presence_of :name
  has_one :user_project
  has_one :user, through: :user_project
end

app/views/projects/index.html.erb
<h1>Projects</h1>
<ul>
  <% @projects.each do |project| %>
    <li>
      <%= link_to project.name, project_path(project) %>
    </li>
  <% end %>
</ul>

app/views/projects/new.html.erb
<%= bootstrap_form_for @project do |f| %>
  <fieldset class="form-group">
    <%= f.text_field :name, label: "name" %>
    <%= f.submit class: "btn btn-primary" %>
  </fieldset>
<% end %>

app/views/projects/show.html.erb
<script type="text/javascript">
var developerKey = "AIzaSyCPV5mM9y9KljCWqWrVWSI2pLI-AveYWk0"
var clientId = "98412712800-9oljtd6so9udt7gtq9otdr26npllibu7"
var accessToken;
function onApiLoad() {
  gapi.load('auth', authenticateWithGoogle);
  gapi.load('picker');
}
function authenticateWithGoogle() {
  window.gapi.auth.authorize({
    'client_id': clientId,
    'scope': ['https://www.googleapis.com/auth/drive.file']
  }, handleAuthentication);
}
function handleAuthentication(result) {
  if(result && !result.error) {
    accessToken = result.access_token;
    $('#choose_pdf').hide();
    setupPicker();
  }
}
function setupPicker() {
  var picker = new google.picker.PickerBuilder()
    .setOAuthToken(accessToken)
    .setDeveloperKey(developerKey)
    .setAppId('98412712800')
    .addView(new google.picker.DocsUploadView())
    .addView(new google.picker.DocsView())
    .setCallback(pickerCallback)
    .build();
  picker.setVisible(true);
}
function pickerCallback(data) {
  var url = 'nothing';
  if (data.action == google.picker.Action.PICKED) {
    var doc = data[google.picker.Response.DOCUMENTS][0];
    var id = doc.id;
    document.getElementById('pdf_file_id').value = id;
    document.forms['new_pdf'].submit();
  } else if (data.action == "cancel") {
    $('#choose_pdf').show();

    $("#choose_pdf").click(function() {
      $('#choose_pdf').hide();
      setupPicker();
    });
  }
}
$("#choose_pdf").click(function() {
  $('#choose_pdf').hide();
  setupPicker();
});

</script>
<%= content_for(:body_attributes) do %>data-no-turbolink<% end %>
<h2><%= @project.name %></h2>
<button id="choose_pdf" class="btn btn-primary">Choose PDF</button>
<%= bootstrap_form_for([@project, Pdf.new]) do |f| %>
  <%= f.hidden_field :file_id %>
  <%= f.hidden_field :project_id, value: @project.id %>
  <%= f.submit "Add PDF", id: "add_pdf", style: "display: none" %>
<% end %>
<script src="https://apis.google.com/js/api.js?onload=onApiLoad"></script>