config/routes.rb
Rails.application.routes.draw do
  # root to: 'sessions#new'
  root to: 'images#new'
  # get 'auth/google_oauth2/callback', to: 'oauth2#redirect'
  get 'auth/google_oauth2/callback', to: 'sessions#create', as: :sign_in
  delete '/sign_out', to: 'sessions#destroy', as: 'sign_out'
  get 'auth/failure', to: redirect('/')
  get '/auth/google_oauth2', as: 'google_oauth2'
  resources :pdfs
  # get '/sign_in', to: 'sessions#new'
  resources :sessions, only: [:create, :destroy]
  # post '/sign_in', to: 'sessions#create', as: 'sessions'
  post 'apply_watermark', to: 'watermarker#apply', as: 'apply_watermark'
  get 'progress/:job_id', to: 'watermarker#percentage_done'

  resources :users, only: [:new, :create]
  resources :images, only: [:new, :create, :show, :index]
  resources :projects, only: [:new, :create, :index, :show] do
    resources :pdfs, only: [:create]
  end

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/models/image.rb
class Image < ActiveRecord::Base
  has_many :sidekiq_jobs, as: :driveable
  belongs_to :user
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :require_google_auth_user

  def new
    set_access_token
    @image = Image.new
  end

  def create
    @image = Image.new(image_params)
    @image.user_id  = current_user.id
    if @image.save
      redirect_to image_path(@image)
    else
      render :new
    end
  end

  def show
    @image = Image.find(params[:id])
    if @image.user == current_user

      @sidekiq_jobs = @image.sidekiq_jobs || []
      set_access_token
      gon.push({
        google_id: @image.google_id
      })

      # if @sidekiq_jobs
      #   gon.watch.push({ job_id: @sidekiq_jobs.job_id })
      # end

      respond_to do |format|
        format.html
        format.js
      end
    else
      redirect_to root_path
    end
  end

  private

  def image_params
    params.require(:image).permit(:google_id, :project_id)
  end

  def set_access_token
    access_token = DriveGenerator.new(current_user.refresh_token).access_token
    @gon_items[:access_token] = access_token
    gon.push(@gon_items)
  end
end

app/views/images/new.html.erb
<%= content_for(:body_attributes) do %>data-no-turbolink<% end %>
<button id="choose_image" class="btn btn-primary">Choose image</button>
<%= bootstrap_form_for(Image.new) do |f| %>
  <%= f.hidden_field :google_id %>
  <%= f.submit "Add image", id: "add_image", style: "display: none" %>
<% end %>

<script src="https://apis.google.com/js/api.js?onload=onApiLoad"></script>

app/views/images/show.html.erb
<div id="job-id-container">
  <div id="job_id">
  </div>
</div>
<div id="img" class="container">
  <div id="output"></div>
  <%= form_tag apply_watermark_path, id: "form" do %>
    <%= hidden_field_tag :id, @image.id, id: 'id' %>
    <%= hidden_field_tag :type, "trump"  %>
    <%= submit_tag "Make This Image Great Again", class: "btn btn-danger" %>
  <% end %>

  <%= form_tag apply_watermark_path, id: "form" do %>
    <%= hidden_field_tag :id, @image.id, id: 'id' %>
    <%= hidden_field_tag :type, "unicorns"  %>
    <%= submit_tag "Make this Image Sparkle", class: "btn btn-success" %>
  <% end %>
</div>

<script src="https://apis.google.com/js/client.js?onload=authMe"></script>
<script src="https://apis.google.com/js/api.js"></script>